version: '3.8'

services:
  db:
    image: postgres:13 # 👉 https://hub.docker.com/_/postgres 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # TODO/TBD: host-path better (in this demo case)? 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=floskl

volumes:
  postgres_data:
