[project]
name = "floskl"
version = "1.0.0"
description = "A simple blog application implemented in Flask."
dependencies = [
    "flask",
    "gunicorn",
    "psycopg2-binary"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"