[project]
name = "floskl"
version = "1.0.0"
description = "Add simple blog application implemented in Flask."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"